import Plot from "react-plotly.js";
import { BarChart2, LineChart, PieChart, ScatterChart, Download, Maximize2, RefreshCw } from "lucide-react";
import { useState } from "react";
import { applyPlotlyTheme, applyPlotlyTraceTheme } from "../utils/plotlyTheme";

interface ChartViewerProps {
  config: any;
  isDarkMode?: boolean;
}

const CHART_META: Record<string, { label: string; icon: any; color: string }> = {
  bar:       { label: "Bar Chart",    icon: BarChart2,    color: "#818cf8" },
  line:      { label: "Line Chart",   icon: LineChart,    color: "#34d399" },
  scatter:   { label: "Scatter Plot", icon: ScatterChart, color: "#f472b6" },
  pie:       { label: "Donut Chart",  icon: PieChart,     color: "#fbbf24" },
  histogram: { label: "Histogram",    icon: BarChart2,    color: "#60a5fa" },
};

export default function ChartViewer({ config, isDarkMode = true }: ChartViewerProps) {
  const [expanded, setExpanded] = useState(false);

  if (!config || !config.data || !config.layout) {
    return (
      <div className="flex flex-col items-center justify-center h-48 gap-3 text-slate-500 rounded-2xl border border-dashed border-slate-300 dark:border-slate-700/50 bg-slate-50 dark:bg-slate-900/30">
        <BarChart2 size={32} className="opacity-30" />
        <p className="text-sm">No chart data available</p>
      </div>
    );
  }

  const chartType = config.data[0]?.type ?? "bar";
  const meta = CHART_META[chartType] ?? { label: "Chart", icon: BarChart2, color: "#818cf8" };
  const Icon = meta.icon;

  /* Apply centralized theme — reacts automatically when isDarkMode changes */
  const layout = applyPlotlyTheme(config.layout, isDarkMode);
  const data   = applyPlotlyTraceTheme(config.data, isDarkMode);

  const handleDownload = () => {
    const el = document.querySelector("#plotly-chart-canvas .js-plotly-plot");
    if ((window as any).Plotly && el) {
      (window as any).Plotly.downloadImage(el, {
        format: "png", filename: "chart", width: 1400, height: 720, scale: 2,
      });
    }
  };

  const chartHeight = expanded ? 560 : 420;

  return (
    <div className="w-full flex flex-col gap-3 animate-scale-in">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span
            className="chart-badge"
            style={{ borderColor: `${meta.color}55`, color: meta.color, background: `${meta.color}18` }}
          >
            <Icon size={10} />
            {meta.label}
          </span>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={() => setExpanded(!expanded)}
            title={expanded ? "Collapse" : "Expand"}
            className="p-1.5 rounded-lg text-slate-500 hover:text-indigo-400 hover:bg-indigo-500/10 transition-all duration-200"
          >
            <Maximize2 size={13} />
          </button>
          <button
            onClick={handleDownload}
            title="Download PNG"
            className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-indigo-400 px-2.5 py-1.5 rounded-lg hover:bg-indigo-500/10 transition-all duration-200"
          >
            <Download size={12} />
            Export
          </button>
        </div>
      </div>

      {/* Chart Canvas */}
      <div
        className="chart-container w-full transition-all duration-500"
        style={{ height: `${chartHeight}px` }}
      >
        <div className="absolute top-3 left-3 flex gap-1.5 z-10">
          <span className="dot dot-red" />
          <span className="dot dot-yellow" />
          <span className="dot dot-green" />
        </div>

        <div id="plotly-chart-canvas" className="w-full h-full pt-3">
          <Plot
            data={data}
            layout={layout}
            useResizeHandler={true}
            style={{ width: "100%", height: "100%" }}
            config={{
              displayModeBar:         true,
              displaylogo:            false,
              responsive:             true,
              modeBarButtonsToRemove: ["lasso2d", "select2d", "autoScale2d", "resetScale2d"],
              toImageButtonOptions:   { format: "png", filename: "chart", scale: 2 },
            }}
          />
        </div>
      </div>

      {/* Footer */}
      <p className="text-[10px] text-slate-600 text-right flex items-center justify-end gap-1">
        <RefreshCw size={9} />
        Generated by AI Visualization Agent
      </p>
    </div>
  );
}
